services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_API_URL: ${TMDB_API_URL}
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Vitejs+Reactjs+TypeScript
    ports:
      - "5173:5173"
    depends_on:
      - backend

    
volumes:
  pgdata: